---
# vars file for osp-facts
os_auth:
  auth_url: http://192.0.2.21:5000
  username: "admin"
  password: "r3dh4t1!"
  project_id: 4e07f423a12f437388a97a533bb9eef9
  project_name: "admin"
  user_domain_name: "Default"
