galaxy_info:
  author: Gary LÃ³pez
  description: Role to install and configure http and tomcat for App Tier application

  license: GPLv3

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
    - http
    - tomcat

dependencies: []
